### PR TITLE
Fixed string interpolation issues in virt-who

### PR DESCRIPTION
**Pull request by vritant**
* fix issues where logging was not interpolating strings right.
* verified all strings with thwo %s are now with correct interpolation in the code base
* also verified there are no strings with more than two %s

### CODE REVIEW

**Comment by vritant** [comment]
@rnovacek please take a look

**Comment by rnovacek** [comment]
According to python logging module docs, "logger.info('message: %', something)" is correct. What is the benefit of having it change to normal string formatting instead of having logger handle that?

**Comment by rnovacek** [comment]
The fix of formatting when throwing the exception if definitely correct, thanks.

**Comment by vritant** [comment]
@rnovacek  you are correct that logging module supports args with string interpolation in that format, However, after conversation with @cnsnyder , we found that log.py delegation to logger breaks that feature.

**Comment by rnovacek** [comment]
@vritant I think it better to fix it in the logger than having to remember not to use that feature. This commit fixed it for me: fd9e259d9dc0f02c5587daa99683a4b647b6bcc8

Is this solution acceptable?

**Comment by vritant** [comment]
Closing PR after verifying the proper fix.

**Pull request closed without merging**
